# Generated by Django 3.2 on 2021-05-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, null=True)),
                ('taskdesc', models.CharField(max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
