# Generated by Django 3.2 on 2021-05-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskdesc',
            new_name='desc',
        ),
    ]
